/**
 * This class is generated by jOOQ
 */
package com.app.camel.model;


import com.app.camel.model.tables.Projects;
import com.app.camel.model.tables.Users;
import com.app.camel.model.tables.UsersHasProjects;
import com.app.camel.model.tables.records.ProjectsRecord;
import com.app.camel.model.tables.records.UsersHasProjectsRecord;
import com.app.camel.model.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>library</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ProjectsRecord, Integer> IDENTITY_PROJECTS = Identities0.IDENTITY_PROJECTS;
    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProjectsRecord> KEY_PROJECTS_PRIMARY = UniqueKeys0.KEY_PROJECTS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<UsersHasProjectsRecord> KEY_USERS_HAS_PROJECTS_PRIMARY = UniqueKeys0.KEY_USERS_HAS_PROJECTS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UsersHasProjectsRecord, UsersRecord> FK_USERS_HAS_PROJECTS_USERS = ForeignKeys0.FK_USERS_HAS_PROJECTS_USERS;
    public static final ForeignKey<UsersHasProjectsRecord, ProjectsRecord> FK_USERS_HAS_PROJECTS_PROJECTS1 = ForeignKeys0.FK_USERS_HAS_PROJECTS_PROJECTS1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ProjectsRecord, Integer> IDENTITY_PROJECTS = createIdentity(Projects.PROJECTS, Projects.PROJECTS.ID);
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ProjectsRecord> KEY_PROJECTS_PRIMARY = createUniqueKey(Projects.PROJECTS, "KEY_projects_PRIMARY", Projects.PROJECTS.ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(Users.USERS, "KEY_users_PRIMARY", Users.USERS.ID);
        public static final UniqueKey<UsersHasProjectsRecord> KEY_USERS_HAS_PROJECTS_PRIMARY = createUniqueKey(UsersHasProjects.USERS_HAS_PROJECTS, "KEY_users_has_projects_PRIMARY", UsersHasProjects.USERS_HAS_PROJECTS.USERS_ID, UsersHasProjects.USERS_HAS_PROJECTS.PROJECTS_ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<UsersHasProjectsRecord, UsersRecord> FK_USERS_HAS_PROJECTS_USERS = createForeignKey(com.app.camel.model.Keys.KEY_USERS_PRIMARY, UsersHasProjects.USERS_HAS_PROJECTS, "fk_Users_has_Projects_Users", UsersHasProjects.USERS_HAS_PROJECTS.USERS_ID);
        public static final ForeignKey<UsersHasProjectsRecord, ProjectsRecord> FK_USERS_HAS_PROJECTS_PROJECTS1 = createForeignKey(com.app.camel.model.Keys.KEY_PROJECTS_PRIMARY, UsersHasProjects.USERS_HAS_PROJECTS, "fk_Users_has_Projects_Projects1", UsersHasProjects.USERS_HAS_PROJECTS.PROJECTS_ID);
    }
}
