/**
 * This class is generated by jOOQ
 */
package com.app.camel.model;


import com.app.camel.model.tables.Projects;
import com.app.camel.model.tables.Users;
import com.app.camel.model.tables.UsersHasProjects;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Library extends SchemaImpl {

    private static final long serialVersionUID = -1553091857;

    /**
     * The reference instance of <code>library</code>
     */
    public static final Library LIBRARY = new Library();

    /**
     * The table <code>library.projects</code>.
     */
    public final Projects PROJECTS = com.app.camel.model.tables.Projects.PROJECTS;

    /**
     * The table <code>library.users</code>.
     */
    public final Users USERS = com.app.camel.model.tables.Users.USERS;

    /**
     * The table <code>library.users_has_projects</code>.
     */
    public final UsersHasProjects USERS_HAS_PROJECTS = com.app.camel.model.tables.UsersHasProjects.USERS_HAS_PROJECTS;

    /**
     * No further instances allowed
     */
    private Library() {
        super("library", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Projects.PROJECTS,
            Users.USERS,
            UsersHasProjects.USERS_HAS_PROJECTS);
    }
}
