/**
 * This class is generated by jOOQ
 */
package com.app.camel.model;


import com.app.camel.model.tables.Projects;
import com.app.camel.model.tables.Users;
import com.app.camel.model.tables.UsersHasProjects;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.projects</code>.
     */
    public static final Projects PROJECTS = com.app.camel.model.tables.Projects.PROJECTS;

    /**
     * The table <code>library.users</code>.
     */
    public static final Users USERS = com.app.camel.model.tables.Users.USERS;

    /**
     * The table <code>library.users_has_projects</code>.
     */
    public static final UsersHasProjects USERS_HAS_PROJECTS = com.app.camel.model.tables.UsersHasProjects.USERS_HAS_PROJECTS;
}
