/**
 * This class is generated by jOOQ
 */
package com.app.camel.model.tables;


import com.app.camel.model.Keys;
import com.app.camel.model.Library;
import com.app.camel.model.tables.records.UserHasProjectRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserHasProject extends TableImpl<UserHasProjectRecord> {

    private static final long serialVersionUID = 781143269;

    /**
     * The reference instance of <code>library.user_has_project</code>
     */
    public static final UserHasProject USER_HAS_PROJECT = new UserHasProject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserHasProjectRecord> getRecordType() {
        return UserHasProjectRecord.class;
    }

    /**
     * The column <code>library.user_has_project.Users_id</code>.
     */
    public final TableField<UserHasProjectRecord, Integer> USERS_ID = createField("Users_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>library.user_has_project.Projects_id</code>.
     */
    public final TableField<UserHasProjectRecord, Integer> PROJECTS_ID = createField("Projects_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>library.user_has_project</code> table reference
     */
    public UserHasProject() {
        this("user_has_project", null);
    }

    /**
     * Create an aliased <code>library.user_has_project</code> table reference
     */
    public UserHasProject(String alias) {
        this(alias, USER_HAS_PROJECT);
    }

    private UserHasProject(String alias, Table<UserHasProjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserHasProject(String alias, Table<UserHasProjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Library.LIBRARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserHasProjectRecord> getPrimaryKey() {
        return Keys.KEY_USER_HAS_PROJECT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserHasProjectRecord>> getKeys() {
        return Arrays.<UniqueKey<UserHasProjectRecord>>asList(Keys.KEY_USER_HAS_PROJECT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserHasProjectRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserHasProjectRecord, ?>>asList(Keys.FK_USERS_HAS_PROJECTS_USERS, Keys.FK_USERS_HAS_PROJECTS_PROJECTS1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHasProject as(String alias) {
        return new UserHasProject(alias, this);
    }

    /**
     * Rename this table
     */
    public UserHasProject rename(String name) {
        return new UserHasProject(name, null);
    }
}
