/**
 * This class is generated by jOOQ
 */
package com.app.camel.model.tables.records;


import com.app.camel.model.tables.UsersHasProjects;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersHasProjectsRecord extends UpdatableRecordImpl<UsersHasProjectsRecord> implements Record4<Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1646327855;

    /**
     * Setter for <code>library.users_has_projects.Users_id</code>.
     */
    public void setUsersId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>library.users_has_projects.Users_id</code>.
     */
    public Integer getUsersId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>library.users_has_projects.Projects_id</code>.
     */
    public void setProjectsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>library.users_has_projects.Projects_id</code>.
     */
    public Integer getProjectsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>library.users_has_projects.project_start_date</code>.
     */
    public void setProjectStartDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>library.users_has_projects.project_start_date</code>.
     */
    public Timestamp getProjectStartDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>library.users_has_projects.project_end_date</code>.
     */
    public void setProjectEndDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>library.users_has_projects.project_end_date</code>.
     */
    public Timestamp getProjectEndDate() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UsersHasProjects.USERS_HAS_PROJECTS.USERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UsersHasProjects.USERS_HAS_PROJECTS.PROJECTS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return UsersHasProjects.USERS_HAS_PROJECTS.PROJECT_START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return UsersHasProjects.USERS_HAS_PROJECTS.PROJECT_END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getProjectsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getProjectStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getProjectEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersHasProjectsRecord value1(Integer value) {
        setUsersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersHasProjectsRecord value2(Integer value) {
        setProjectsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersHasProjectsRecord value3(Timestamp value) {
        setProjectStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersHasProjectsRecord value4(Timestamp value) {
        setProjectEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersHasProjectsRecord values(Integer value1, Integer value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersHasProjectsRecord
     */
    public UsersHasProjectsRecord() {
        super(UsersHasProjects.USERS_HAS_PROJECTS);
    }

    /**
     * Create a detached, initialised UsersHasProjectsRecord
     */
    public UsersHasProjectsRecord(Integer usersId, Integer projectsId, Timestamp projectStartDate, Timestamp projectEndDate) {
        super(UsersHasProjects.USERS_HAS_PROJECTS);

        set(0, usersId);
        set(1, projectsId);
        set(2, projectStartDate);
        set(3, projectEndDate);
    }
}
